import { ParsableLanguageConfig } from "../../../types";
export const config: ParsableLanguageConfig = {
  patterns: [
    { type: "comment", regex: /^(\/\/.*|\/\*[\s\S]*?\*\/)/ },
    {
      type: "string",
      regex: /^("([^"\\]|\\.)*"?|'([^'\\]|\\.)*'?|`([^`\\]|\\.)*`?)/,
    },
    { type: "number", regex: /^\d+(\.\d+)?/ },
    {
      type: "operator",
      regex:
        /^(===|==|!==|!=|<=|>=|=>|\.\.\.|&&|\|\||\+\+|--|\+=|-=|\*=|\/=|\+=|&=|\|=|\^=|<<=|>>=|>>>=|[+\-*/%=&|^~<>!?:,;.])/,
    },
    { type: "brackets1", regex: /^[\(\)\[\]\{\}]/ },
    { type: "variable", regex: /^[a-zA-Z_$][a-zA-Z0-9_$]*/ },
    { type: "default", regex: /^[ \t\r]+/ },
  ],
  keywords1: new Set([
    "const",
    "var",
    "let",
    "function",
    "class",
    "import",
    "export",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "break",
    "continue",
    "try",
    "catch",
    "finally",
    "throw",
    "new",
    "this",
    "super",
    "extends",
    "implements",
    "interface",
    "type",
    "enum",
    "async",
    "await",
    "from",
    "as",
    "declare",
    "namespace",
    "module",
    "public",
    "private",
    "protected",
    "static",
    "readonly",
    "abstract",
  ]),
  keywords2: new Set([
    "true",
    "false",
    "null",
    "undefined",
    "NaN",
    "Infinity",
    "void",
    "typeof",
    "instanceof",
    "in",
    "of",
    "delete",
    "this",
    "console",
    "window",
    "document",
    "global",
    "process",
  ]),
  detectFunctions: true,
};
